# Site settings
title: Anvar Turobov
email: anvar.turobov@gmail.com
url: https://anvarturobov.github.io
description: "An aspiring Full Stack Web Developer with extensive experience in Business Development, B2C Sales and Technical Recruitment.
Having worked with many awesome developers and inspiring tech companies during my career in B2B/B2C Sales and Recruitment, I have decided to finally realise my long standing goal of learning coding by attending General Assembly’s Web Development Immersive program. 12-Weeks, all day everyday, web development bootcamp, where I experienced working in an Agile environment, attending daily Scrums, learning the key aspects of programming while building full-stack web applications and APIs using JavaScript and Ruby."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Anvar Turobov

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
- title: twitter
  url: https://twitter.com/AnvarTurobov
- title: github
  url: http://github.com/anvarturobov
- title: linkedin
  url: https://uk.linkedin.com/in/anvarturobov

# Build settings
markdown: kramdown
permalink: pretty
