url: https://anvarturobov.github.io
baseurl:

# Site settings
title: Anvar Turobov 
email: anvar.turobov@gmail.com
description: "Hi name name is Anvar, I am a Web Developer with extensive Business Development Experience"

# Color settings (hex-codes without the leading hash-tag)
color:
  # primary: fed136
  # secondary: fec503  
  primary: 005eff
  secondary: 0900ff
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AnvarTurobov
  - title: github
    url: http://github.com/anvarturobov
  - title: linkedin
    url: https://uk.linkedin.com/in/anvar777
    # - title: facebook
    #   url: 
    # - title: stack-overflow
    #   url: http://stackoverflow.com/questions/tagged/jekyll
    # - title: bitbucket 
    #   url: http://bitbucket.org/jekyll


# Build settings
markdown: kramdown
permalink: pretty